[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qa-agent"
version = "0.1.0"
description = "My Python package"
authors = [{ name="Your Name", email="you@email.com" }]
dependencies = []

[project.scripts]
qa_agent = "qa_agent.main:main"
